### ISSUE TITLE
Kaitlyn Hopkins

### ISSUE THREAD

**Issue by kaitlynehopkins** [umiami-web-design/html#3]
https://kaitlynehopkins.github.io/resume.html

**Comment by kaitlynehopkins** [comment]
updated with revisions from meeting Tuesday, Oct. 24, 2017––thank you again for your time and for meeting with me, it was very helpful!

**Comment by ebrown15** [comment]
Thanks for coming by Hack Hours. The tweaks look good. Excellent job.
