### ISSUE TITLE
Goh Si Qian Belinda 

### ISSUE THREAD

**Issue by bellygx** [umiami-web-design/html#5]
http://bellygx.github.io/resume.html

**Comment by ebrown15** [comment]
Thanks for attending extra hours to discuss and review your code.

A couple suggestions: Break up the content "NTU- Participant In Regional Strategic Communication Management Module" a little better. Don't use a dash (-), rather use tags to mark these up separately. Also, if you only have one bullet point, consider using a paragraph instead.
