### ISSUE TITLE
Kirsten McGarvey

### ISSUE THREAD

**Issue by kirstenmcgarvey** [umiami-web-design/html#7]
https://kirstenmcgarvey.github.io/resume.html

**Comment by ebrown15** [comment]
Thanks for coming by Hack Hours, but some of the changes we discussed are still missing (i.e. headers which match the nav links -- Education, About Me, etc.).

**Comment by kirstenmcgarvey** [comment]
I had a problem with getting the file from my USB drive back into my GitHub repo so I was going to ask you in the beginning of class how to fix it! I will try to see what I can do now.


I have the revised version saved on my laptop and thumb drive, just not up on GitHub.


Thank you,

Kirsten McGarvey

________________________________
